---
- name: CONFIGURE DEVICE HOSTNAME
  hosts: csr
  gather_facts: false
  connection: local
  become: yes
  become_method: enable

  tasks:
  - name: update hostname
    ios_system:
      hostname: "CSR-virtual"
