---
- name: CONFIGURE DEVICE HOSTNAME
  hosts: iosxe_reserved
  gather_facts: false
  connection: local
  become: yes
  become_method: enable

  tasks:
  - name: update hostname
    ios_system:
      hostname: "iosxe_reserved-virtual"
